[package]
name = "csprng"
version = "1.0.5"
description = "Cryptographically secure pseudo-random number generator using the ChaCha algorithm"
repository = "https://github.com/temokoki/IC_CSPRNG"
keywords = [ "random", "rng", "prng", "csprng", "chacha" ]
license = "MIT"

[dependencies]
base = "0.13.2"

[dev-dependencies]
bench = "1.0.0"